[package]
name = "mcmc_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
csv = "1.1.6"
serde = { version = "1.0.147", features = ["serde_derive"] }
